cat/urls.py
from django.urls import path
from . import views
app_name = "cat"
urlpatterns = [
    path('',views.MainView.as_view(),name="all"),
    path('breed/',views.BreedView.as_view(),name="breedview"),
    path('breed/add',views.BreedCreate.as_view(),name="breedcreate"),
    path('breed/update/<int:pk>/',views.BreedUpdate.as_view(),name="breedupdate"),
    path('breed/delete/<int:pk>/',views.BreedDelete.as_view(),name="breeddelete"),
    path('cat/',views.CatCreate.as_view(),name="catcreate"),
    path('cat/catupdate/<int:pk>/',views.CatUpdate.as_view(),name="catupdate"),
    path('cat/catdelete/<int:pk>/',views.CatDelete.as_view(),name="catdelete"),
    ]

catcrud/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cat/',include('cat.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
]

cat/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Breed(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Cat(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

home/models.py
from django.db import models

# Create your models here.

cat/forms.py
from django.forms import ModelForm
from cat.models import Cat
class CatForm(ModelForm):
    class Meta:
        model = Cat
        fields = '__all__'

cat/views.py
from django.shortcuts import render,get_object_or_404
from django.views import View
from cat.models import Cat,Breed
from django.contrib.auth.mixins import LoginRequiredMixin
from cat.forms import CatForm
from django.urls import reverse,reverse_lazy
from django.http import HttpResponse,HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView


# Create your views here.
class MainView(LoginRequiredMixin,View):
    def get(self,request):
        breed_count = Breed.objects.all().count()
        cat_value = Cat.objects.all()
        ctx = {"breed_count":breed_count,"cat_value":cat_value}
        return render(request,'cat/main_view.html',ctx)

class BreedView(LoginRequiredMixin,View):
    def get(self,request):
        breed_value = Breed.objects.all();
        return render(request,'cat/breed_view.html',{"breed_value":breed_value})

class BreedCreate(LoginRequiredMixin,CreateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy("cat:breedview")

class BreedUpdate(LoginRequiredMixin,UpdateView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy("cat:breedview")

class BreedDelete(LoginRequiredMixin,DeleteView):
    model = Breed
    fields = '__all__'
    success_url = reverse_lazy("cat:breedview")

class CatCreate(LoginRequiredMixin,View):
    def get(self,request):
        form = CatForm()
        return render(request,'cat/cat_create.html',{"form":form});

    def post(self,request):
        form = CatForm(request.POST)
        if not form.is_valid():
            return render(request,'cat/cat_create.html',{"form":form});
        cat = form.save()
        return HttpResponseRedirect(reverse("cat:all"))

class CatUpdate(LoginRequiredMixin,View):
    def get(self,request,pk):
        value = get_object_or_404(Cat,pk=pk)
        form = CatForm(instance=value)
        return render(request,'cat/cat_create.html',{"form":form})

    def post(self,request,pk):
        value = get_object_or_404(Cat,pk=pk)
        form = CatForm(request.POST,instance=value)
        if not form.is_valid():
            return render(request,'cat/cat_create.html',{"form":form})
        cat = form.save()
        return HttpResponseRedirect(reverse("cat:all"))

class CatDelete(LoginRequiredMixin,View):
    def get(self,request,pk):
        cat = get_object_or_404(Cat,pk=pk)
        #form = CatForm(instance=value)
        return render(request,'cat/cat_delete.html',{"cat":cat})

    def post(self,request,pk):
        value = get_object_or_404(Cat,pk=pk)
        value.delete()
        return HttpResponseRedirect(reverse("cat:all"))
            
    
        

home/views.py
from django.shortcuts import render

# Create your views here.

cat/templates/cat/breed_confirm_delete.html
<!DOCTYPE html>
<html>
<head><title>Delete Page</title></head>
<body>
  <h3>Are you sure for delete {{breed.name}}</h3>
  <form action="" method="post">
	{% csrf_token %}
	
	<input type="submit" value="delete">
        <input type="button" onclick="window.location='{% url 'cat:all' %}';return false;" value="cancle">
  </form>
</body>
</html>

cat/templates/cat/breed_form.html
<!DOCTYPE html>
<html>
<head><title>Add Page</title></head>
<body>
  <form action="" method="post">
	{% csrf_token %}
	{{form.as_p}}
	<input type="submit" value="add">
        <input type="button" onclick="window.location='{% url 'cat:all' %}';return false;" value="cancle">
  </form>
</body>
</html>

cat/templates/cat/breed_view.html
<!DOCTYPE html>
<html>
<head><title>Breed Page</title></head>
<body>
  <h1>Breed List</h1>
  {% if breed_value %}
	<ul>
	    {% for breed in breed_value %}
		<li>{{breed.name}}(
                     <a href="{% url 'cat:breedupdate' breed.id%}">Update</a>|<a href="{% url 'cat:breeddelete' breed.id%}">Delete</a>)
                </li>
            {% endfor %}
        </ul>
  {% else %}
        <p>Please add Breed</p>
  {% endif %}
  
  <a href="{% url 'cat:all' %}">Back to main</a>|<a href="{% url 'cat:breedcreate' %}">Add to breed</a>
</body>
</html>

cat/templates/cat/cat_create.html
<!DOCTYPE html>
<html>
<head><title>Cat Create Page</title></head>
<body>
  <form action="" method="post">
	{% csrf_token %}
        <table>
	{{form.as_table}}
        </table>
	<input type="submit" value="Add">
        <input type="button" onclick="window.location='{% url 'cat:all' %}';return false;" value="Cancle">
  </form>
</body>
</html>

cat/templates/cat/cat_delete.html
<!DOCTYPE html>
<html>
<head><title>Cat Create Page</title></head>
<body>
  <h3>Arr you sure for delete {{cat.nickname}}?</h3>
  <form action="" method="post">
	{% csrf_token %}
        
	<input type="submit" value="Confirm">
        <input type="button" onclick="window.location='{% url 'cat:all' %}';return false;" value="Cancle">
  </form>
</body>
</html>

cat/templates/cat/main_view.html
<!DOCTYPE html>
<html>
<head><title>Main Page</title></head>
<body>
  <h1>Cat List</h1>
  {% if cat_value %}
	<ul>
	    {% for cat in cat_value %}
		<li> 
		    {{cat.nickname}}|foods({{cat.foods}})|weight({{cat.weight}})
                    (<a href="{% url 'cat:catupdate' cat.id%}">Update</a>|<a href="{% url 'cat:catdelete' cat.id%}">Delete</a>)
		</li>
	    {% endfor %}
	</ul>
  {% else %}
	<p>Please add Cat.</p>
  {% endif %}
  
  {% if breed_count > 0 %}
	<p><a href="{% url 'cat:catcreate' %}">Add to cat</a></p>
  {% else %}
        <p>Please add breed</p>
  {% endif %}

  <a href="{% url 'cat:breedview' %}">Breed list</a>|<a href="{% url 'cat:breedcreate' %}">Add to breed</a><br>
  <a href="{% url 'logout' %}?next={% url 'cat:all' %}">Logout</a>
</body>
</html>